Several improvements
Symantec/slack-autoarchive pull request #4
Opened 2017-02-19 07:00 UTC by adamkaplan

- Fulfill requirement to not delete with 5+ members and recent bot
  messages
- Send admin message to Slack in Dry Run mode for debugging
- Send only 1 admin message, no spam on first run (I got 950 spams!)
- Add whitelist.txt support, 1 exclusion rule per line
- Support for POST requests (Admin messages can get too long for GET)

2017-02-27 18:50 UTC, JohnTheodore requested changes
Thoughts on setting the default member limit to unlimited, and opting into a limit?

2017-02-27 18:50 UTC, JohnTheodore commented on slack-autoarchive.py
> +MIN_MEMBERS        = 5
I want to archive channels even if there are arbitrary users in there, 50, 500, etc. Would you modify your PR so MIN_MEMBERS is unlimited by default, and you can set say an environment variable to limit archiving to only channels below 5 members to restrict archiving to small channels?

2017-03-03 04:52 UTC, adamkaplan commented on slack-autoarchive.py
> +MIN_MEMBERS        = 5
Sure, sounds fine.  I only chose 5 due to the README. (However, so far 5 has proved to work well for my 1700 channel Slack instance!)

2017-03-07 18:14 UTC, JohnTheodore approved these changes

2017-03-07 18:15 UTC, merged

2017-03-07 18:15 UTC, JohnTheodore commented
LGTM